### ISSUE TITLE
Consistent code

### ISSUE THREAD

**Issue by NouraldinS** [MuhmmadAwd/VanLife#10]
https://github.com/MuhmmadAwd/VanLife/blob/5c65ff21841dd3bab573b60312de3cf02027de67/src/components/FetchVans.jsx#L6

It should be clear, at all times, even before seeing any code, at least to you as the developer, where is the state living and where is it coming from.
Sometimes you're using react-dom hooks to get search URL and parameters, sometimes you pass it through props, what is the rule?

**Comment by xMohammedAwad** [comment]
I don't need to pass searchParams at all here `typeFilter` is enough. but I will consider that next times
