### ISSUE TITLE
Programming with resources in mind

### ISSUE THREAD

**Issue by NouraldinS** [MuhmmadAwd/VanLife#2]
https://github.com/MuhmmadAwd/VanLife/blob/ec0748c9f1fa346e969b31b6b6d478d9dd8d27eb/src/pages/Login.jsx#L15-L30

It's rare to find websites that stress either the CPU or the GPU, but memory is an easy-to-abuse resource which sometimes is handled very poorly by developers, one issue that causes memory leaks is not memoizing functions and values.

This login component will rerender every time a character is typed into the username and password fields, and on every render, react is going to tell Javascript to redeclare these handleSubmit and handleChange functions. At this scale, this is not an issue, and this is only possibly going to cost less than a KB of memory, but maintaining this behavior across an entire platform is how you end up with websites that demand 2+ GBs of memory.

**Comment by xMohammedAwad** [comment]
### just for the record (explain from Nour)

> When you declare a function inside any component, imagine that the code for that function has a place in memory. Because when you re-render, the function gets thrown out of memory and recreated. This is where `useCallback` comes in.

> `useCallback` preserves the function's place in memory so that it doesn't get re-declared every time. In general, all functions inside a component should be wrapped in `useCallback` if you find yourself using them frequently in that component. If you don't, you might be thinking about your code incorrectly, and you can probably optimize and potentially eliminate some of the functions.
> 
> In some cases, these functions might not even belong inside the component. This is the purpose of `useCallback`. It's like a memoization technique that helps improve performance.
> 
> Now, let's talk about `useMemo`. It's relatively easier to understand where to use it, and its function is more related to CPU usage than memory.
> 
> Imagine you have a costly operation, like mapping a large dataset for a table, performing a reduce operation on an array, or doing recursive read/write operations on an object. In all these cases where your code's complexity is greater than O(1), you can use `useMemo` to optimize and cache the results, so you don't have to recalculate them every render.
>
