### ISSUE TITLE
Write configurable code

### ISSUE THREAD

**Issue by NouraldinS** [MuhmmadAwd/VanLife#3]
https://github.com/MuhmmadAwd/VanLife/blob/ec0748c9f1fa346e969b31b6b6d478d9dd8d27eb/src/App.jsx#L37-L60

Don't copy paste code, and keep a mentality of writing for larger teams and preparing for larger projects, and even writing code for non-techs or low-techs
In this example, you would have much more accessible code with smaller footprint if you rewrite your routes as a configurable object in this format
```ts
type Route = {
  path: string;
  component: React.ReactNode;
  children: Route[]
}
```
This object would be easy to reconfigure or modify even for someone who doesn't know React, and it's more compact and clear on the long run when you have tens of pages to account for.

Same ideology for your Header.jsx and HostLayout.jsx

**Comment by xMohammedAwad** [comment]
first commit I changed the Routes then the second Header & Host Layout and I found that HostVanDetail have the same thing and I did it for all of them .
