### ISSUE TITLE
Importing just to run

### ISSUE THREAD

**Issue by NouraldinS** [MuhmmadAwd/VanLife#4]
https://github.com/MuhmmadAwd/VanLife/blob/ec0748c9f1fa346e969b31b6b6d478d9dd8d27eb/src/App.jsx#L22

What you intended here is understandable, but generally avoid calling files just for the sake of running them, it could change easy-to-fix issues and bugs into nightmares to trace.

**Comment by xMohammedAwad** [comment]
what should I do instead? document why I'm importing it.
