### ISSUE TITLE
Extremely dangerous behavior

### ISSUE THREAD

**Issue by NouraldinS** [MuhmmadAwd/VanLife#5]
https://github.com/MuhmmadAwd/VanLife/blob/ec0748c9f1fa346e969b31b6b6d478d9dd8d27eb/src/api.js#L14-L19

No matter what you think of the project or its future, even if it's just a throwaway project which you're going to delete, always, ALWAYS save your keys, passwords and IDs in private config files, it is an extremely dangerous behavior to write sensitive keys directly into the code.

**Comment by xMohammedAwad** [comment]
I know but this Firebase config it's not secret right? 
https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
